// Demo user data for the admin dashboard (Week 3 brief: no DB required).
// The currently signed-in admin is merged in at runtime.

export const demoUsers = [
  {
    id: "u1",
    name: "Aarav Sharma",
    email: "aarav.sharma@gmail.com",
    image: null,
    role: "user",
    status: "active",
    joinedAt: "2026-07-06",
    lastActive: "2026-08-02",
    signIns: 34,
  },
  {
    id: "u2",
    name: "Priya Nair",
    email: "priya.nair@outlook.com",
    image: null,
    role: "user",
    status: "active",
    joinedAt: "2026-07-09",
    lastActive: "2026-08-01",
    signIns: 27,
  },
  {
    id: "u3",
    name: "Rohan Mehta",
    email: "rohan@kavyalabs.ai",
    image: null,
    role: "admin",
    status: "active",
    joinedAt: "2026-07-01",
    lastActive: "2026-08-02",
    signIns: 58,
  },
  {
    id: "u4",
    name: "Sneha Kulkarni",
    email: "sneha.k@gmail.com",
    image: null,
    role: "user",
    status: "active",
    joinedAt: "2026-07-15",
    lastActive: "2026-07-30",
    signIns: 12,
  },
  {
    id: "u5",
    name: "Vikram Reddy",
    email: "v.reddy@yahoo.com",
    image: null,
    role: "user",
    status: "deactivated",
    joinedAt: "2026-07-11",
    lastActive: "2026-07-19",
    signIns: 6,
  },
  {
    id: "u6",
    name: "Ananya Iyer",
    email: "ananya.iyer@gmail.com",
    image: null,
    role: "user",
    status: "active",
    joinedAt: "2026-07-26",
    lastActive: "2026-08-02",
    signIns: 9,
  },
  {
    id: "u7",
    name: "Karan Patel",
    email: "karan.p@gmail.com",
    image: null,
    role: "user",
    status: "active",
    joinedAt: "2026-07-29",
    lastActive: "2026-07-31",
    signIns: 4,
  },
];

// Signups per day for the last 7 days (demo analytics series)
export const signupTrend = [
  { day: "Jul 27", signups: 1 },
  { day: "Jul 28", signups: 0 },
  { day: "Jul 29", signups: 2 },
  { day: "Jul 30", signups: 1 },
  { day: "Jul 31", signups: 1 },
  { day: "Aug 1", signups: 3 },
  { day: "Aug 2", signups: 2 },
];
